on:
  pull_request:
  merge_group:

name: Fuzz

jobs:
  fuzz:
    strategy:
      matrix:
        targets: [ethernet-frame-parser, ieee802154-frame-parser, ipv4-packet-parser, ipv6-packet-parser]
    runs-on: ubuntu-22.04
    env:
      RUSTUP_TOOLCHAIN: nightly
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz
      - name: Fuzz
        run: cargo fuzz run ${{ matrix.targets }} -- -max_total_time=30
